#
# Copyright (c) 2022 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/CHISTERA-PATTERN/pattern.github.io.
#
# SPDX-License-Identifier: CC-BY-4.0
#
name: Deploy to Github Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - name: Install Material for MkDocs
        run: pip install mkdocs-material mkdocs-minify-plugin
      - name: Deploy site
        run: mkdocs gh-deploy --force