#
# Copyright (c) 2024 - for information on the respective copyright owner
# see the NOTICE file and/or the repository https://github.com/CHISTERA-PATTERN/pattern.github.io.
#
# SPDX-License-Identifier: CC-BY-4.0
#
name: Deploy to Github Pages
on:
  workflow_dispatch:
  push:
    branches:
      - main  # Or master, depending on your default branch name

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          # This makes the GitHub Actions token available to the MkDocs command
          # It's necessary for the `gh-deploy` command to push to the gh-pages branch.
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          # This caches installed pip packages between runs to speed up the build process
          path: |
            ~/.cache/pip
            .cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Material for MkDocs
        # Include any other dependencies or plugins required by your MkDocs setup
        run: |
          pip install mkdocs-material mkdocs-minify-plugin
        
      - name: Build
        run: mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          # This uses a built-in GitHub token for authentication with the GitHub Pages server
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site  # Directory where MkDocs outputs the built site, check your mkdocs.yml
